name: cvescan

on:
  workflow_dispatch:

permissions: write-all

env:
  GINKGO_VERSION: "v2.9.5"

jobs:
  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.x

      - uses: actions/setup-go@v5
      - name: generate CVE.json
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b ./
          go install github.com/devops-kung-fu/bomber@latest 
          ./syft scan . -o cyclonedx-json -vv  > sbom.json 
          cat sbom.json
          bomber scan ./sbom.json --output=json --debug > cve.json
          cat cve.json

      - name: add doc with LLM
        id: Lint_with_LLM
        uses: SamYuan1990/OpenAI_CodeAgent-action@main
        with:
          baseURL: https://api.deepseek.com
          model: deepseek-chat
          dirPath: '/workdir'
          runType: CVEDependency
          apiKey: ${{ secrets.API_KEY }}
          dryRun: true

      - name: Upload Artifact for process log
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: GenAI_output
          path: GenAI_output/
