name: Mark up go doc Demo

on:
  workflow_dispatch:

permissions: write-all

env:
  GINKGO_VERSION: "v2.9.5"

jobs:
  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.x

      - name: Install dependencies
        run: |
          command -v ginkgo || go install github.com/onsi/ginkgo/v2/ginkgo@${{ env.GINKGO_VERSION }}

      - name: unittest
        id: unittest
        run: |
          make test PROFILE=y
          wget https://raw.githubusercontent.com/SamYuan1990/OpenAI_CodeAgent-action/refs/heads/main/goASTBin -O ./goASTBin && chmod a+x ./goASTBin

      - name: add doc with LLM
        id: Lint_with_LLM
        uses: SamYuan1990/OpenAI_CodeAgent-action@main
        with:
          baseURL: https://api.deepseek.com
          model: deepseek-chat
          dirPath: '/workdir'
          maxIterations: 1
          runType: godoc
          apiKey: ${{ secrets.API_KEY }}

      - name: output check
        shell: bash
        run: |
          echo '${{ steps.Lint_with_LLM.outputs.LLMresponse }}'
          echo '${{ steps.Lint_with_LLM.outputs.final_prompt }}'
          echo '${{ steps.Lint_with_LLM.outputs.avg_prompt_precent }}'
          echo '${{ steps.Lint_with_LLM.outputs.avg_content_precent }}'
          echo '${{ steps.Lint_with_LLM.outputs.avg_time_usage }}'
          echo '${{ steps.Lint_with_LLM.outputs.avg_inputToken }}'
          echo '${{ steps.Lint_with_LLM.outputs.avg_outputToken }}'

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.MyPATToken }} # 使用 GitHub 提供的 token
          branch: auto-pr-branch # 新分支名称
          base: master # 目标分支
          title: 'Automated PR: Update generated files with go doc'
          body: 'This is an automated pull request created by GitHub Actions.'
          commit-message: 'Auto-generated changes for go doc'
          sign-commits: true
          labels: automated # 可选：为 PR 添加标签
